- name: Configure asterisk.conf
  become: true
  ansible.builtin.template:
    src: asterisk.conf.j2
    dest: /etc/asterisk/asterisk.conf
    owner: asterisk
    group: asterisk
    mode: "u=rw,g=r"
  notify: Restart asterisk

- name: Configure pjsip
  become: true
  ansible.builtin.template:
    src: pjsip.conf.j2
    dest: /etc/asterisk/pjsip.conf
    owner: asterisk
    group: asterisk
    mode: "u=rw,g=r"
  notify: Restart asterisk

- name: Configure extensions
  become: true
  ansible.builtin.template:
    src: extensions.conf.j2
    dest: /etc/asterisk/extensions.conf
    owner: asterisk
    group: asterisk
    mode: "u=rw,g=r"
  notify: Restart asterisk

- name: Configure voicemail
  become: true
  ansible.builtin.template:
    src: voicemail.conf.j2
    dest: /etc/asterisk/voicemail.conf
    owner: asterisk
    group: asterisk
    mode: "u=rw,g=r"
  notify: Restart asterisk