---
- name: Install asterisk
  ansible.builtin.include_tasks:
    file: install.yml
  tags:
    - install_asterisk

- name: Configure asterisk
  ansible.builtin.import_tasks:
    file: configure.yml
  tags:
    - configure_asterisk